export const CUSTOM_ERRORS: string[] = [
  "uncaughtException",
  "SIGINT",
  "unhandledRejection",
];

export const GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";

export const WS_DATA_FRAME_RULES = {
  // WS RULES
  MIN_FRAME_SIZE: 2,
  // WS Payload Related Fields
  SMALL_DATA_SIZE: 125,
  MEDIUM_DATA_SIZE: 65535,
  MEDIUM_SIZE_DATA_FLAG: 126,
  LARGE_SIZE_DATA_FLAG: 127,
  MEDIUM_SIZE_CONSUMPTION_BYTES: 2,
  LARGE_SIZE_CONSUMPTION_BYTES: 8,
  MASK_KEY_LENGTH: 4,
  // WS OPCODES
  OPCODE_TEXT: 0x01,
  OPCODE_BINARY: 0x02,
  OPCODE_CLOSE: 0x08,
  OPCODE_PING: 0x09,
  OPCODE_PONG: 0x0a,
};
